
import type { ClothingItem, NavLink } from '@/lib/types';
import { Home, Shirt, Heart, ShoppingCart, User, Mail, Wand2, Info } from 'lucide-react';

export const APP_NAME = "თბილისი სთაილს";

export const NAV_LINKS: NavLink[] = [
  { key: 'nav-home', href: '/', label: 'მთავარი', icon: Home },
  { key: 'nav-catalog', href: '/catalog', label: 'კატალოგი', icon: Shirt },
  { key: 'nav-contact', href: '/contact', label: 'კონტაქტი', icon: Mail },
];

export const USER_NAV_LINKS: NavLink[] = [
  { key: 'user-nav-favorites', href: '/favorites', label: 'რჩეულები', icon: Heart },
  { key: 'user-nav-cart', href: '/cart', label: 'კალათა', icon: ShoppingCart },
  { key: 'user-nav-profile', href: '/profile', label: 'პროფილი', icon: User },
];

export const MOCK_CLOTHING_CATEGORIES: string[] = [
  "ჩოხა",
  "ქართული კაბა",
  "ფაფახი",
  "ხევსურული",
  "აქსესუარები",
];

export const MOCK_CLOTHING_ITEMS: ClothingItem[] = [
  {
    id: '1',
    name: 'ტრადიციული ჩოხა (შავი)',
    description: 'კლასიკური შავი ჩოხა, ქართული სიამაყისა და ვაჟკაცობის სიმბოლო. დამზადებულია მაღალი ხარისხის მატყლისგან და დახვეწილი ვერცხლის ნაქარგებით.',
    price: 250,
    imageUrls: ['https://placehold.co/500x700.png?text=Chokha+Black+1', 'https://placehold.co/500x700.png?text=Chokha+Black+2'],
    dataAiHint: 'georgian chokha',
    category: 'ჩოხა',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['შავი', 'ვერცხლის ნაქარგი'],
    slug: 'traditional-chokha-black',
    discountPercentage: 10,
    brandName: "თბილისი სთაილს",
    averageRating: 4.5,
    reviewCount: 25,
    stock: 10,
  },
  {
    id: '2',
    name: 'ელეგანტური ქართული კაბა (წითელი)',
    description: 'განსაცვიფრებელი წითელი ქართული კაბა, იდეალურია ოფიციალური ღონისძიებებისთვის. გამორჩეულია ნაზი ოქროსფერი დეტალებითა და თავისუფალი სილუეტით.',
    price: 320,
    imageUrls: ['https://placehold.co/500x700.png?text=Kartuli+Dress+Red'],
    dataAiHint: 'kartuli dress',
    category: 'ქართული კაბა',
    sizes: ['S', 'M', 'L'],
    colors: ['წითელი', 'ოქროსფერი დეტალები'],
    slug: 'elegant-kartuli-dress-red',
    brandName: "თბილისი სთაილს",
    averageRating: 4.8,
    reviewCount: 18,
    stock: 7,
  },
  {
    id: '3',
    name: 'ავთენტური ფაფახი',
    description: 'ტრადიციული ფაფახი, დამზადებული ნამდვილი ცხვრის ტყავისგან. კავკასიური მთის ჩაცმულობის განუყოფელი ნაწილი.',
    price: 80,
    imageUrls: ['https://placehold.co/500x700.png?text=Papakhi+Hat'],
    dataAiHint: 'papakhi hat',
    category: 'ფაფახი',
    sizes: ['ერთი ზომა'],
    colors: ['ბუნებრივი თეთრი', 'შავი'],
    slug: 'authentic-papakhi-hat',
    discountPercentage: 15,
    averageRating: 4.2,
    reviewCount: 30,
    stock: 15,
  },
  {
    id: '4',
    name: 'ხევსურული საბრძოლო ტუნიკა',
    description: 'ხევსურული საბრძოლო ტუნიკა, შემკული ტრადიციული გეომეტრიული ორნამენტებით. ხელით შეკერილი გამძლე ქსოვილისგან.',
    price: 180,
    imageUrls: ['https://placehold.co/500x700.png?text=Khevsuruli+Tunic'],
    dataAiHint: 'khevsuruli tunic',
    category: 'ხევსურული',
    sizes: ['M', 'L', 'XL'],
    colors: ['მუქი ლურჯი', 'მრავალფეროვანი ორნამენტები'],
    slug: 'khevsuruli-warrior-tunic',
    brandName: "მთის ძალა",
    averageRating: 4.0,
    reviewCount: 12,
    stock: 5,
  },
  {
    id: '5',
    name: 'ვერცხლის ქამარი ყანწისთვის',
    description: 'მდიდრულად მორთული ქამარი, შექმნილი ტრადიციული ყანწისთვის. გამორჩეულია რთული ვერცხლის ნაკეთობითა და ტყავით.',
    price: 150,
    imageUrls: ['https://placehold.co/500x700.png?text=Silver+Belt'],
    dataAiHint: 'georgian belt',
    category: 'აქსესუარები',
    sizes: ['რეგულირებადი'],
    colors: ['ვერცხლი', 'შავი ტყავი'],
    slug: 'silver-qama-dagger-belt',
    averageRating: 4.9,
    reviewCount: 22,
    stock: 20,
  },
  {
    id: '6',
    name: 'ქალის ნაქარგი ბლუზა',
    description: 'ულამაზესი ქალის ბლუზა ტრადიციული ქართული ნაქარგებით. დამზადებულია სუნთქვადი სელისგან.',
    price: 120,
    imageUrls: ['https://placehold.co/500x700.png?text=Embroidered+Blouse'],
    dataAiHint: 'georgian blouse',
    category: 'ქართული კაბა',
    sizes: ['S', 'M', 'L'],
    colors: ['თეთრი', 'წითელი ნაქარგი'],
    slug: 'embroidered-womens-blouse',
    discountPercentage: 5,
    brandName: "თბილისი სთაილს",
    averageRating: 3.8,
    reviewCount: 9,
    stock: 8,
  },
   {
    id: '7',
    name: 'მამაკაცის ახალუხი (კრემისფერი)',
    description: 'კომფორტული და მოდური მამაკაცის ახალუხი კრემისფერ ბამბაში. იდეალურია ყოველდღიური ტარებისთვის ან კულტურული ღონისძიებებისთვის.',
    price: 160,
    imageUrls: ['https://placehold.co/500x700.png?text=Akhalukhi+Beige'],
    dataAiHint: 'akhalukhi men',
    category: 'ჩოხა',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['კრემისფერი', 'ყავისფერი კანტი'],
    slug: 'mens-akhalukhi-beige',
    averageRating: 4.3,
    reviewCount: 15,
    stock: 12,
  },
  {
    id: '8',
    name: 'ბავშვის ჩოხის კომპლექტი',
    description: 'სრული ჩოხის კომპლექტი ბავშვებისთვის, მოიცავს ტუნიკას, ქამარს და ქუდს. ხელმისაწვდომია სხვადასხვა მკვეთრ ფერებში.',
    price: 130,
    imageUrls: ['https://placehold.co/500x700.png?text=Kids+Chokha'],
    dataAiHint: 'childrens chokha',
    category: 'ჩოხა',
    sizes: ['4წ', '6წ', '8წ', '10წ'],
    colors: ['წითელი', 'ლურჯი', 'მწვანე'],
    slug: 'childrens-chokha-set',
    brandName: "პატარა გმირი",
    // No rating for this one to test undefined case
    stock: 9,
  }
];

export const FOOTER_LINKS: NavLink[] = [
    { key: 'footer-about', href: '/about', label: 'ჩვენ შესახებ', icon: Info },
    { key: 'footer-shipping', href: '/shipping', label: 'მიწოდება და დაბრუნება' },
    { key: 'footer-privacy', href: '/privacy', label: 'კონფიდენციალურობის პოლიტიკა' },
    { key: 'footer-terms', href: '/terms', label: 'მომსახურების პირობები' },
];
