# yaml-language-server: $schema=https://firebase.google.com/static/apphosting/schema.json

runConfig:
  cpu: 1
  memoryMiB: 1024
  concurrency: 80
  maxInstances: 10

apphosting:
  - backendId: "my2025"
    location: "europe-west4"
    rootDir: "workspace"
env:
    # Get these values from your Firebase Project Settings > Your apps > Web App (Config)
    - variable: NEXT_PUBLIC_FIREBASE_API_KEY
      value: "AIzaSyDy2Y2gCnftrx_lFcDITiMhn0tOcwEps98" # <-- Replaced placeholder!
    - variable: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      value: "my2025-d8323.firebaseapp.com"
    - variable: NEXT_PUBLIC_FIREBASE_PROJECT_ID
      value: "my2025-d8323"
    - variable: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      value: "my2025-d8323.firebasestorage.app" # <-- Using the value from your config
    - variable: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      value: "520072870997"
    - variable: NEXT_PUBLIC_FIREBASE_APP_ID
      value: "1:520072870997:web:56ee6a91eb54ea398728dc"
    # If you use Analytics:
    - variable: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
      value: "G-ZEYBHBF3DY" # <-- Replaced placeholder!
    # If you use Realtime Database (uncomment if needed):
    # - variable: NEXT_PUBLIC_FIREBASE_DATABASE_URL
    #     value: https://myonlineshop2025-5ffcf.firebaseio.com # Or your specific RTDB URL
    - variable: GEMINI_API_KEY
      value: "AIzaSyBdiq2nvkChQWno-sbHVmoAN8CsEVarQEo" # Consider using Secret Manager for this!

headers:
  - path: /_next/static
    headers:
      - key: Cache-Control
        value: public, max-age=31536000, immutable
  - path: /static
    headers:
      - key: Cache-Control
        value: public, max-age=31536000, immutable
